TBashaBari/TBashaBari/Controllers/TenantViewsBillController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TBashaBari.Data;
using TBashaBari.Models;
using System.Data.SqlClient;
using TBashaBari.Controllers;

namespace BashaBari.Controllers
{
    public class TenantViewsBillController : Controller
    {
        List<BillInformation> _billinformationlist = new List<BillInformation>();

        private readonly ApplicationDbContext _db;

        public TenantViewsBillController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            FetchBillInfo();
            return View(_billinformationlist);
        }

        //:::::::::::::::::::::::::::::::::::::::::GET_CREATE
        public IActionResult Create()
        {
            return View();
        }
        //::::::::::::::::::::::::::::::::::::::::POST_CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(BillInformation obj)
        {
            if (ModelState.IsValid)
            {
                _db.BillInformation.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //:::::::::::::::::::::::::::::::::::::::GET_EDIT
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var obj = _db.BillInformation.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }
        //::::::::::::::::::::::::::::::::::::::POST_EDIT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(BillInformation obj)
        {
            if (ModelState.IsValid)
            {
                _db.BillInformation.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //:::::::::::::::::::::::::::::::::::::::GET_DELETE
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var obj = _db.BillInformation.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }
        //::::::::::::::::::::::::::::::::::::::POST_DELETE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(BillInformation obj)
        {
            if (ModelState.IsValid)
            {
                _db.BillInformation.Remove(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::://
        //:::::::::::::::::::::::::::::         custom methods        ::::::::::::::::::::::::::::::::://
        private void FetchBillInfo()
        {
            //User.Identity.Name returns current logged in user's email
            string queryString = "SELECT TOP 1000 [BillId],[OwnerEmail],[TenantEmail],[BillTime],[WaterAmount],[WaterPaid],[WaterVerified],[ElectricAmount]," +
                                        "[ElectricPaid],[ElectricVerified],[RentAmount],[RentPaid],[RentVerified],[GasAmount],[GasPaid],[GasVerified] " +
                                        "FROM [BashaBariWeb].[dbo].[BillInformation] " +
                                        "WHERE [TenantEmail] = '" + User.Identity.Name + "' " +
                                        "ORDER BY [BillTime] DESC";
            //to clear the list initially
            if (_billinformationlist.Count > 0)
            {
                _billinformationlist.Clear();
            }

            //database operation
            DatabaseConnection obj = new DatabaseConnection();
            obj.DbConnect();
            while (obj.ExeQuery(queryString).Read())
            {
                _billinformationlist.Add(new BillInformation
                {
                    BillId = int.Parse(obj.ExeQuery(queryString)["BillId"].ToString()),
                    OwnerEmail = obj.ExeQuery(queryString)["OwnerEmail"].ToString(),
                    TenantEmail = obj.ExeQuery(queryString)["TenantEmail"].ToString(),
                    BillTime = obj.ExeQuery(queryString)["BillTime"].ToString(),

                    WaterAmount = obj.ExeQuery(queryString)["WaterAmount"].ToString(),
                    WaterPaid = obj.ExeQuery(queryString)["WaterPaid"].ToString(),
                    WaterVerified = obj.ExeQuery(queryString)["WaterVerified"].ToString(),

                    ElectricAmount = obj.ExeQuery(queryString)["ElectricAmount"].ToString(),
                    ElectricPaid = obj.ExeQuery(queryString)["ElectricPaid"].ToString(),
                    ElectricVerified = obj.ExeQuery(queryString)["ElectricVerified"].ToString(),

                    RentAmount = obj.ExeQuery(queryString)["RentAmount"].ToString(),
                    RentPaid = obj.ExeQuery(queryString)["RentPaid"].ToString(),
                    RentVerified = obj.ExeQuery(queryString)["RentVerified"].ToString(),

                    GasAmount = obj.ExeQuery(queryString)["GasAmount"].ToString(),
                    GasPaid = obj.ExeQuery(queryString)["GasPaid"].ToString(),
                    GasVerified = obj.ExeQuery(queryString)["GasVerified"].ToString(),
                });
            }
            obj.CloseDbConnect();
        }

        
        //::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::://
    }
}

TBashaBari/TBashaBari/Views/TenantViewsBill/Create.cshtml
@*@model TBashaBari.Models.OwnerNotice
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<form method="post" asp-action="Create" class="text-center">
    <div class="border p-3">
        <div class="form-group">
            <h2 class="text-primary font-weight-bold pl-5">Add a Notice</h2>
        </div>
        <input id="today" asp-for="NoticeTime" class="form-control" hidden />
        <input asp-for="OwnerEmail" class="form-control" value="@UserManager.GetUserName(User)" hidden />
        <input asp-for="NoticeText" class="form-control text-center py-4" />
        <br>
        <input type="submit" class="btn btn-success w-20 m-2" value="Post" />
        <a asp-action="Index" class="btn btn-primary w-20 m-2">
            Back
        </a>

    </div>
</form>

<script>
    var today = new Date().toISOString().substr(0, 10);
    var currentTime = new Date();
    var currentHours = currentTime.getHours();
    var currentMinutes = currentTime.getMinutes();

    // Pad the currentMinutes with leading zeros, if required
    currentMinutes = (currentMinutes < 10 ? "0" : "") + currentMinutes;

    // Pad currentHours with leading zeros, if required
    currentHours = (currentHours < 10 ? "0" : "") + currentHours;

    // Compose the string for display
    var currentTimeString = currentHours + ":" + currentMinutes;

    // Final Time
    document.querySelector("#today").value = today + " at " + currentTimeString;
</script>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}*@

TBashaBari/TBashaBari/Views/TenantViewsBill/Delete.cshtml
@*@model TBashaBari.Models.OwnerNotice

<form method="post" class="text-center">
    <input asp-for="NoticeId" hidden />
    <div class="border p-3">
        <div class="form-group">
            <h2 class="text-primary pl-3 font-weight-bold">Are you sure, you want to delete the Notice?</h2>
        </div>
        <input asp-for="NoticeText" class="form-control" hidden />
        <input asp-for="NoticeTime" class="form-control" hidden />
        <input asp-for="OwnerEmail" class="form-control" hidden />
        <input type="submit" class="btn btn-danger w-20 m-2" value="Delete" />
        <a asp-action="Index" class="btn btn-primary w-20 m-2">
            Back
        </a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}*@

TBashaBari/TBashaBari/Views/TenantViewsBill/Edit.cshtml
@model TBashaBari.Models.OwnerNotice

<form method="post" class="text-center">
    <div class="border p-3">
        <div class="form-group">
            <h2 class="text-primary font-weight-bold pl-5">Edit Notice</h2>
        </div>
        <input asp-for="NoticeId" hidden />
        <input id="today" asp-for="NoticeTime" class="form-control" hidden />
        <input asp-for="OwnerEmail" class="form-control" hidden />
        <input asp-for="NoticeText" class="form-control text-center py-4" />
        <br>
        <input type="submit" class="btn btn-success w-20 m-2" value="Update" />
        <a asp-action="Index" class="btn btn-primary w-20 m-2">
            Back
        </a>

    </div>
</form>

<script>
    var today = new Date().toISOString().substr(0, 10);
    var currentTime = new Date();
    var currentHours = currentTime.getHours();
    var currentMinutes = currentTime.getMinutes();

    // Pad the currentMinutes with leading zeros, if required
    currentMinutes = (currentMinutes < 10 ? "0" : "") + currentMinutes;

    // Pad currentHours with leading zeros, if required
    currentHours = (currentHours < 10 ? "0" : "") + currentHours;

    // Compose the string for display
    var currentTimeString = currentHours + ":" + currentMinutes;

    // Final Time
    document.querySelector("#today").value = today + " at " + currentTimeString + "  [Edited]";
</script>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

TBashaBari/TBashaBari/Views/TenantViewsBill/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using System.Data.SqlClient;
@using TBashaBari.Controllers;

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@{
    string GetUserFullName(string _Email)
    {
        //database operation to get user's fullname
        DatabaseConnection ob = new DatabaseConnection();
        string FullName = ob.getUserFullName(_Email);
        return FullName;
    }
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary font-weight-bold">Your Bills</h2>
        </div>
        @*<div class="col-6 text-right">
            <a asp-controller="TenantViewsBill" asp-action="Select" class="btn btn-primary">
                Post New Bill
            </a>
        </div>*@
    </div>

    <br /><br />

    @{
        if (Model.Count != 0)
        {
            foreach (var obj in Model)
            {
                <div class="card w-80 mb-5 mx-5" style="background-color: gainsboro">
                    <div class="row no-gutters">
                        <div class="col-sm-2">
                            <div class="login-form-icon text-center">
                                <i class="fas fa-user-circle fa-6x text-secondary p-3"></i>
                            </div>
                        </div>
                        <div class="col-sm-10">
                            <div class="card-body">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="font-weight-bold m-0 p-0">@GetUserFullName(obj.TenantEmail) </h5>
                                    <h5 class="font-weight-lighter m-0 p-0">@obj.BillTime</h5>
                                </div>
                                <small>[ @obj.TenantEmail ]</small>
                                <br />
                                <br />

                                <table class="table table-sm">
                                    <thead>
                                        <tr>
                                            <th>Bill Type</th>
                                            <th>Amount</th>
                                            <th>Paid</th>
                                            <th>Verified</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>Water</td>
                                            <td>@obj.WaterAmount</td>
                                            <td>@obj.WaterPaid</td>
                                            <td>@obj.WaterVerified</td>
                                        </tr>
                                        <tr>
                                            <td>Electric</td>
                                            <td>@obj.ElectricAmount</td>
                                            <td>@obj.ElectricPaid</td>
                                            <td>@obj.ElectricVerified</td>
                                        </tr>
                                        <tr>
                                            <td>Gas</td>
                                            <td>@obj.GasAmount</td>
                                            <td>@obj.GasPaid</td>
                                            <td>@obj.GasVerified</td>
                                        </tr>
                                        <tr>
                                            <td>Rent</td>
                                            <td>@obj.RentAmount</td>
                                            <td>@obj.RentPaid</td>
                                            <td>@obj.RentVerified</td>
                                        </tr>
                                    </tbody>
                                </table>

                                <div class="text-lg-right">
                                    <a asp-controller="TenantViewsBill" asp-route-Id="@obj.BillId" asp-action="Edit" class="btn btn-primary ml-3">
                                        Check Paid
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        }
        else
        {
            <h5 class="p-4">You haven't posted any notice yet.</h5>
        }
    }
</div>